### ISSUE TITLE
Remove some fields for new users to sign in more easily

### ISSUE THREAD

**Issue by p19y** [N0r3f/cdr#2]
![Screenshot 2022-10-28 at 14-09-41 Profil utilisateur](https://user-images.githubusercontent.com/73939446/198583862-3848f3db-b95c-4272-aa87-bce385b620a2.png)

**Comment by N0r3f** [comment]
Unfortunately, we need to know the names of the professionals who wish to participate in the adventure.
I agree that this is far too busy.
We'll do it another way.
The goal will be to have the professional fill out his or her own profile.
Tx bro !
